<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\ABS.Payments.Core\ABS.Payments.Core.csproj" />
    <ProjectReference Include="..\ABS.Payments.Infrastructure\ABS.Payments.Infrastructure.csproj" />
  </ItemGroup>

</Project>
